[project]
name = "protoc-wrapper"
version = "0.1.0"
description = "Repackage official protoc compiler as Python wheels"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pendulum>=3.1.0",
    "requests>=2.32.3",
    "wheel>=0.45.1",
]

[tool.uv]
package = false
