name: Sync protobuf releases
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to look back'
        required: true
        type: number
        default: 7
      version_suffix:
        description: 'Version suffix to append to the version'
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      # For PyPI's trusted publishing.
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Make wheels
        run: uv run sync_releases.py --days ${{ github.event.inputs.days || 7 }} --version-suffix ${{ github.event.inputs.version_suffix || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish wheels
        run: |
          if [ -z "$(ls -A ./dist)" ]; then
            echo "No files to publish."
            exit 0
          fi
          uv publish -v
